# Generated by Django 4.2.13 on 2024-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_city_shippingaddress_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'FOOD'), ('drink', 'DRINK')], default='', max_length=6),
        ),
    ]
