# Generated by Django 4.2.13 on 2024-05-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], default='', max_length=10),
        ),
    ]
