# Generated by Django 4.2.11 on 2024-05-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
