# Generated by Django 3.1.7 on 2024-05-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_digital'),
        ('store', '0006_alter_product_category'),
    ]

    operations = [
    ]
