# Generated by Django 3.1.7 on 2024-05-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20240524_1101'),
        ('store', '0008_product_stock'),
    ]

    operations = [
    ]
