# Generated by Django 4.2.13 on 2024-05-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20240524_1101'),
        ('store', '0008_product_stock'),
    ]

    operations = [
    ]
