# Generated by Django 3.1.7 on 2024-05-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_price'),
        ('store', '0011_product_image'),
    ]

    operations = [
    ]
