name: Publish Docker image

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run : |
          docker build . -t alvanm/netnibbles:latest

      - name: publish
        run: |
          docker login -u alvanm -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push alvanm/netnibbles:latest